'use client';

import { useState } from 'react';
import { trackEvent } from '@/lib/audit';

interface AnalysisData {
  overallScore: number;
  headlineScore: number;
  summaryScore: number;
  experienceScore: number;
  skillsScore: number;
  keywordsScore: number;
  recommendations: {
    headline: { score: number; feedback: string; suggestions: string[] };
    summary: { score: number; feedback: string; suggestions: string[] };
    experience: { score: number; feedback: string; suggestions: string[] };
    skills: { score: number; feedback: string; suggestions: string[] };
    keywords: { score: number; feedback: string; missingKeywords?: string[]; presentKeywords?: string[] };
  };
}

function generateMarkdown(data: AnalysisData): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let md = `# LinkedIn Profile Analysis Report\n`;
  md += `**Date:** ${date}\n\n`;
  md += `## Overall Score: ${data.overallScore}/100\n\n`;
  md += `| Section | Score |\n|---------|-------|\n`;
  md += `| Headline | ${data.headlineScore}/100 |\n`;
  md += `| Summary | ${data.summaryScore}/100 |\n`;
  md += `| Experience | ${data.experienceScore}/100 |\n`;
  md += `| Skills | ${data.skillsScore}/100 |\n`;
  md += `| Keywords | ${data.keywordsScore}/100 |\n\n`;

  const sections = [
    { key: 'headline' as const, title: 'Headline' },
    { key: 'summary' as const, title: 'Summary' },
    { key: 'experience' as const, title: 'Experience' },
    { key: 'skills' as const, title: 'Skills' },
    { key: 'keywords' as const, title: 'Keywords' },
  ];

  for (const section of sections) {
    const rec = data.recommendations[section.key];
    if (!rec) continue;

    md += `## ${section.title} (${rec.score}/100)\n\n`;
    md += `${rec.feedback}\n\n`;

    if ('suggestions' in rec && rec.suggestions) {
      md += `### Suggestions\n`;
      for (const s of rec.suggestions) {
        md += `- ${s}\n`;
      }
      md += `\n`;
    }

    if (section.key === 'keywords' && 'missingKeywords' in rec) {
      if (rec.missingKeywords && rec.missingKeywords.length > 0) {
        md += `**Missing Keywords:** ${rec.missingKeywords.join(', ')}\n\n`;
      }
      if (rec.presentKeywords && rec.presentKeywords.length > 0) {
        md += `**Present Keywords:** ${rec.presentKeywords.join(', ')}\n\n`;
      }
    }
  }

  md += `---\n*Generated by ProfilePro AI*\n`;
  return md;
}

export function ExportButton({ data }: { data: AnalysisData }) {
  const [copied, setCopied] = useState(false);

  const handlePrint = () => {
    trackEvent('export', 'You', 'You exported results as PDF');
    window.print();
  };

  const handleCopyMarkdown = async () => {
    const markdown = generateMarkdown(data);
    trackEvent('export', 'You', 'You exported results as Markdown');
    try {
      await navigator.clipboard.writeText(markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const textarea = document.createElement('textarea');
      textarea.value = markdown;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="flex items-center gap-2 print:hidden">
      <button
        onClick={handlePrint}
        className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 border border-white/10 text-zinc-300 text-sm font-medium hover:bg-white/10 hover:text-white transition-all"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18.75 9H5.25" />
        </svg>
        Export PDF
      </button>
      <button
        onClick={handleCopyMarkdown}
        className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 border border-white/10 text-zinc-300 text-sm font-medium hover:bg-white/10 hover:text-white transition-all"
      >
        {copied ? (
          <>
            <svg className="w-4 h-4 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
            </svg>
            Copied!
          </>
        ) : (
          <>
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
            </svg>
            Copy Markdown
          </>
        )}
      </button>
    </div>
  );
}
